{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Acessos",
   "type": "stat",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gunicorn_requests", "legendFormat": "Total" },
    { "expr": "gunicorn_response_code", "legendFormat": "{{status}}" }
   ]
  },
  { "title": "Dados", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Workers",
   "type": "gauge",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "gunicorn_workers", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Quartis",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 8, "x": 6, "y": 9 },
   "targets": [
    { "expr": "gunicorn_request_duration", "legendFormat": "Quant. {{quantile}}%" }
   ]
  },
  {
   "title": "Média",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 10, "x": 14, "y": 9 },
   "targets": [
    {
     "expr": "avg(gunicorn_request_duration_sum)",
     "legendFormat": "Média"
    }
   ]
  }
 ]
}